version: '2'
services:
  mongo:
   image: percona/percona-server-mongodb
   restart: always
   volumes:
     - /docker/mongo/app/data:/data
   ports:
    - "32017:27017"
  goapp:
    build: .
    restart: always
    environment:
     - PORT=5000
     - MONGO_HOST=mongo
    ports:
     - "5000:5000"
    links:
     - mongo
